name: facebook_app
description: A Facebook clone app project to display my thought process on how to build an app following clean and scoped approach.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  #Easy and Fast internationalizing and localization
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
  internet_connection_checker: ^0.0.1+3
  
  flutter_secure_storage: ^5.0.0
  device_preview: ^1.0.0
  shimmer: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
 
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/stories/
    - assets/images/profiles/
 
